// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxcczifkldwuelhibbwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Y2N6aWZrbGR3dWVsaGliYndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjUzNjYsImV4cCI6MjA2NTU0MTM2Nn0.KsYrIB-R6_OdUTXd8jGH4fDwpvkBq2Pz1k2332YTZso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);