// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Create a nullable supabase client
export const supabase: SupabaseClient<Database> | null = 
  (supabaseUrl && supabaseAnonKey) 
    ? createClient<Database>(supabaseUrl, supabaseAnonKey)
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";